name: valheim-server  # Name of the container group
apiVersion: '2019-12-01'
location: eastus
tags: {}
type: Microsoft.ContainerInstance/containerGroups
properties: # Properties of container group
  containers: # Array of container instances in the group
  - name: valheim # Name of an instance
    properties: # Properties of an instance
      image: lloesche/valheim-server # Container image used to create the instance
      ports: # External-facing ports exposed on the instance, must also be set in group ipAddress property 
      - protocol: tcp
        port: 2457
      - protocol: tcp
        port: 80
      - protocol: udp
        port: 2456
      environmentVariables:
      - name: SERVER_NAME
        value: <label>
      - name: WORLD_NAME
        value: <world>
      - name: SERVER_PASS
        value: <password>
      - name: SERVER_PUBLIC
        value: true
      - name: STATUS_HTTP
        value: true
      - name: BACKUPS
        value: false
      resources: # Resource requirements of the instance
        requests:
          memoryInGB: 4
          cpu: 1
      volumeMounts: # Array of volume mounts for the instance
      - name: gamedata
        mountPath: /config
      - name: gameconfig
        mountPath: /opt/valheim
  restartPolicy: always
  ipAddress: # IP address configuration of container group
    ports:
      - protocol: tcp
        port: 2457
      - protocol: udp
        port: 2456
      - protocol: tcp
        port: 80
    type: Public
    dnsNameLabel: <label>
  osType: Linux
  volumes: # Array of volumes available to the instances
  - name: gamedata
    azureFile:
      shareName: <data-share>
      storageAccountName: <account>
      storageAccountKey: <key>
  - name: gameconfig
    azureFile:
      shareName: <config-share>
      storageAccountName: <account>
      storageAccountKey: <key>