version: "3"

services: 
  valheim: 
    image: lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - gamedata:/config
      - gameconfig:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    environment:
      - SERVER_NAME=<label>
      - WORLD_NAME=<world>
      - SERVER_PASS=<password>
      - SERVER_PUBLIC=true
      - STATUS_HTTP=true
      - STATUS_HTTP_PORT=8080
    restart: always
    stop_grace_period: 2m

volumes:
  gamedata:
    driver: azure_file
    driver_opts:
      share_name: vhserver-data
      storage_account_name: vhserver
  gameconfig:
    driver: azure_file
    driver_opts:
      share_name: vhserver-config
      storage_account_name: vhserver